#! /bin/sh
echo '####################Start automatic deployment####################'
path=$(pwd) #current path
backupTime=$(date +'%Y%m%d_%H_%M_%S')
tomcatPath=/home/dev/apache-tomcat-8.5.42/ #Specify the tomcat file directory name
cd $tomcatPath/bin || exit #Enter the bin directory of tomcat
PID=$(ps -fu root|grep tomcat|grep -v grep|awk '{print $2}') # scene
if [ -z "$PID" ];then
 echo "no tomcat process"
else
 echo "Start safe end process"
 kill -15 "$PID"
# ./shutdown.sh #Stop tomcat service
sleep 5
  if [ -z "$PID" ];then
    echo 'process'"$PID"'Has ended safely'
  else
    echo 'The process did not end safely. Start forced end'
    kill -9 "$PID"
    echo 'process'"$PID"'Has ended'
  fi
fi
sleep 1 #Sleep for 1s
cd ../webapps || exit #Enter the webapps directory of tomcat
rm -fr helloWorld #Delete helloWorld file directory
echo 'File directory deletion complete'
mv helloWorld.war ./backup/helloWorld.war."$backupTime" #Backup to backup
echo 'Backup complete'
sleep 1 #Sleep for 1s
cp "$path"/helloWorld.war ./ #Copy war to webapps path
sleep 1 #Sleep for 1s
cd ../bin || exit
./startup.sh #Start tomcat service
echo '####################End of deployment####################'

